service: ${self:custom.project.name}

frameworkVersion: ">=1.2.0 <2.0.0"

custom:
  project: ${file(./project.yml)}
  private: ${file(./private.yml)}

provider:
  name: aws
  deploymentBucket: ${self:custom.project.deploymentBucket}
  runtime: python2.7

package:
  individually: true
  exclude:
    - ./**

functions:
  InviteSlack:
    handler: invite-slack/handler.endpoint
    package:
      include:
        - invite-slack/**
  RecordDB:
    handler: record-db/handler.endpoint
    package:
      include:
        - record-db/**
  RecordAC:
    handler: record-ac/handler.endpoint
    package:
      include:
        - record-ac/**

stepFunctions:
  stateMachines:
    signup:
      events:
        - http:
            path: signup
            method: PUT
            cors: true # Wish it worked but it does NOT: https://github.com/horike37/serverless-step-functions/issues/37
      definition: # ${file(workflow.yml)}
        Comment: "Community sign-up workflow"
        StartAt: RecordDB
        States:
          RecordDB:
            Type: Task
            Resource: arn:aws:lambda:${self:custom.private.region}:${self:custom.private.accountId}:function:${self:custom.project.name}-dev-RecordDB
            Next: RecordAC
            ResultPath: $.results.RecordDB
          RecordAC:
            Type: Task
            Resource: arn:aws:lambda:${self:custom.private.region}:${self:custom.private.accountId}:function:${self:custom.project.name}-dev-RecordAC
            Next: InviteSlack
            ResultPath: $.results.RecordAC
          InviteSlack:
            Type: Task
            # Resource: ${self.resources.Outputs.InviteSlackLambdaArn.Value} too bad this doesn't work, chicken-n-egg problem
            Resource: arn:aws:lambda:${self:custom.private.region}:${self:custom.private.accountId}:function:${self:custom.project.name}-dev-InviteSlack
            ResultPath: $.results.InviteSlack
            End: true

resources:
  Outputs:
    InviteSlackLambdaName:
      Description: Invite Slack Lambda function name
      Value:
        Ref: InviteSlackLambdaFunction
      Export:
        Name: ${self:custom.project.name}-FunctionName
    InviteSlackLambdaArn:
      Description: The Name of the Photo Assignments Fail Lambda
      Value:
        'Fn::GetAtt': [ InviteSlackLambdaFunction, Arn ]
      Export:
        Name: ${self:custom.project.name}-FunctionArn

plugins:
  - serverless-step-functions